### ISSUE TITLE
BookKeeper client is not able recover from restarted bookie

### ISSUE THREAD

**Issue by fpj** [pravega/pravega-operator#116]
The [BookieFailoverTest](https://github.com/pravega/pravega/blob/master/test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java) 
case (Pravega system tests) is failing consistently because the segment store is not able to recover from a bookie that is stopped and later restarted (there are exactly three bookies and the ledger ensemble requires three bookies).

The problem, observed from the logs, is that the BK client that the segment store instantiates detects that the bookie has crashed and it tries to get a new bookie. As part of the process of selecting a new bookie, it excludes bookies that it has used previously in the ledger. The client continues to attempt a connection to the previous bookie periodically, but the new incarnation happens to have a different IP address. The client uses the bookie host name, which keeps resolving to the old address and any connection to it fails.

Here is some relevant detail. In this line:

https://github.com/pravega/pravega-operator/blob/99901541159c81056f160a97274baeb6ea337ae6/pkg/controller/pravega/bookie.go#L180 

We ask the bookies to use the host name rather than the IP address. The client receives the host name as the client ID and uses the host name to connect.

This test case used to pass up to the Pravega `r0.3`. After `r0.3`, we introduced this change:

https://github.com/pravega/pravega/pull/2833

A solution here would be to make sure that the bookie host name is unique despite restarts.

**Comment by adrianmo** [comment]
After investigation with @fpj, the issue seems to come from BookKeeper resolving the IP address once and caching the result. Assuming that the IP address will not change over time. Evidences for that can be seen [here](https://github.com/apache/bookkeeper/blob/branch-4.5/bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java#L48) and [here](https://github.com/apache/bookkeeper/blob/branch-4.5/bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java#L76). Note that we are currently using BookKeeper 4.5.

Starting on 4.7, BookKeeper became more cloud and container friendly and started allowing IP address to change if the client is initialize with a host name. This can be seen [here](https://github.com/apache/bookkeeper/blob/branch-4.7/bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java#L50) and [here](https://github.com/apache/bookkeeper/blob/branch-4.7/bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java#L96). 

As a workaround, we could make a change in the operator to expose `BK_useHostNameAsBookieID` so that it can be set to `false`, but I'd rather focus on updating the BookKeeper version used in Pravega to 4.7 or newer. The following PR is a WiP to do such thing: https://github.com/pravega/pravega/pull/3192

**Comment by eolivelli** [comment]
@adrianmo @fpj sorry for late reply.
Before seeing your response I was preparing the same answer.
The fix here is to upgrade BK as you are already doing or cherry pick that change and create a custom version or 'shade' bookkeeper jar.
I prefer the upgrade but it is an important library upgrade so it can be dangerous for 0.4 release.

**Comment by EronWright** [comment]
To add a bit of Kubernetes flavor here, each pod is assigned a hostname, a corresponding IP, and a persistent volume.   They'll remain the same for the life of the pod; if, for whatever reason, one of those things is lost, then the pod reaches an end-of-life.  A stateful set will then spawn a wholly new pod (new name/ip/volume).

**Comment by adrianmo** [comment]
A workaround has been merged in https://github.com/pravega/pravega-operator/pull/117. However I'll keep this issue open until https://github.com/pravega/pravega/pull/3192 is merged and we can revert `BK_useHostNameAsBookieID` back to `true`.
