### ISSUE TITLE
heapdump file size is too big

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega-operator#282]
### Description

We are using emptyDir right now to store heapdump if OOM happens. However in the recent experiments on AWS, the OOM pod gets evicted by the K8s because the heapdump file is too big, more than 17G.
Not sure why heap dump file can be this huge and how to store such huge heap dump?

**Comment by Prabhaker24** [comment]
This issue is not reproducible for now will keep a watch if we hit this issue again so removing priority from p1 and it still needs investigation, one more problem that I see here is in place of storing heap dump in Ephemeral storage we can store it in Persistence storage but the thing with that is we will have to specify the size for it and even that can get completely occupied as well.

**Comment by Prabhaker24** [comment]
Closing this issue as we have not hit this issue for a long time feel free to open it if we hit the issue again.
