### ISSUE TITLE
Providing alternate ways to do image version validation for non-production environments

### ISSUE THREAD

**Issue by SrishT** [pravega/pravega-operator#394]
### Description
Users should be allowed to specify whether the charts are being for development purposes or not. While deploying the operator for development purposes, the users should either be allowed to provide their own version map, or should be allowed to skip version validation altogether. This is required since currently there doesn't seem to be any other way to use the pravega charts (without modifying them) to deploy pravega versions that are not already part of the version map.

### Importance
must have

### Location
pravega helm charts

**Comment by pbelgundi** [comment]
Pravega version validation can be made **dynamic** or **skipped** in the following ways:
(1) Dynamic version support- Existing helm chart should be modified so the map for "versions-config-map" template should be accepted in values.yaml file instead of being hard-coded.
(2) Skipping Version Validation - Operator supports a "webhook" flag (_similar to the "test-mode" flag_) which can be set to **false** to disable "version-validation". I would not recommend doing this for production environments
