### ISSUE TITLE
Operator versioning strategy

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#53]
The operator will use SemVer for versioning. The initial release will be `0.1.0`, with the following meaning:

- `0`: indicates initial development. Anything may change at any time. The public API should not be considered stable.
- `1`: first set of features.
- `0`: no bug fixes yet.

After each release, we will immediately append the `+git` suffix to the version number to indicate that there are changes on top of that version. E.g. after the first release, we will change the version to `0.1.0+git`. This is what the Operator SDK and other operators are also doing.

**Comment by maddisondavid** [comment]
I would also suggest that we switch to using Git Tags to track and record versions.  If we tag with a SemVer such as 0.0.1 the following will give us a simple version number to use.

```
$ git describe --always --tags --dirty --long
0.0.1-0-g067f261

# Now commit
$ git commit ........
$ git describe --always --tags --dirty --long
0.0.1-1-gfce7ed9

# Now retag
$ git tag 0.1.1
$ git describe --always --tags --dirty --long
0.1.1-0-gfce7ed9
```
This provides the version number from the tag, plus the number of commits since that tag and finally the actual latest commit meaning we don't need a `+git` to be appended.  What's more we have the version number external to the code AND we mark the source code at the same time.

An example of this approach is Skaffold: https://github.com/GoogleContainerTools/skaffold/blob/master/Makefile#L37
