### ISSUE TITLE
Admission Controller for PravegaCluster resource

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-operator#7]
Currently the resource contains the Bookkeeper and Pravega image definitions.  The operator should have sensible defaults set in its configuration and apply these to the resource via a mutating Admission Controller.

**Comment by adrianmo** [comment]
Blocked by: https://github.com/operator-framework/operator-sdk/issues/269

**Comment by adrianmo** [comment]
Related to #88

**Comment by adrianmo** [comment]
The admission controller should also attempt to mutate the values in the `options` block.

https://github.com/pravega/pravega-operator/blob/78d99444549be1060e6883e9dea13c75b74c9fca/pkg/apis/pravega/v1alpha1/pravega.go#L95

Option values are expected to be strings, surrounded by double quotes, otherwise the operator framework will fail to parse it and reject the CR. It'd be interesting if the admission controller could transform to strings any values passed as options.
