### ISSUE TITLE
Refactor the `PravegaCluster` CRD

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-operator#85]
I feel that the `PravegaCluster` CRD has become unwieldy and should be factored into three component parts reflecting the topology.
1. `pravega.dellemc.com/v1alpha1/Controller`
2. `pravega.dellemc.com/v1alpha1/SegmentStore`
3. `pravega.dellemc.com/v1alpha1/Bookie`

One of the benefits is improved interoperability with `kubectl scale` which could target each resource separately.  Perhaps `kubectl rollout` too.

In defense of the idea, the value proposition of an operator is to provide active management of a service or application, using CRDs as appropriate to establish the goal state.   Consolidating everything into a single resource is not an essential aspect.  I think it utterly normal to use numerous resources together to realize a service.   Also, I'm not too concerned about any duplication of configuration data that may occur.

Note that all the above CRDs would be implemented by the `pravega-operator`.  I am NOT suggesting three operators.

Other good reasons:
1.  per-component status.  Each of SSS, controller, BK should have status, and by splitting into separate resources, each gets to use the status section in a standard way.
2. independent versioning of each resource type.
3. simpler reconciliation loop.   the logic of operating each component (SSS,ctrl,BK) could be made more independent.
4. more flexibility.  For example, imagine a scenario where one deploys a tier-2 BK in addition to tier-1 as proposed in [PDP 22 - BK based Storage (Tier 2) for Pravega](https://github.com/pravega/pravega/wiki/PDP-22:-BK-based-Storage-(Tier-2)-for-Pravega).   This could be described more easily if BK resource was a standalone building block.

**Comment by EronWright** [comment]
@adrianmo let's please consider this for post-beta but pre-GA.

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Operator: Provide CR status information](https://trello.com/c/cVwUz0nj/111-operator-provide-cr-status-information)

**Comment by adrianmo** [comment]
@EronWright I have my concerns about the benefits of splitting the `PravegaCluster` resource into `Controller`, `SegmentStore`, and `Bookie` resources. I'll add some comments...

> One of the benefits is improved interoperability with `kubectl scale` which could target each resource separately.

Agreed, that would be a nice-to-have feature. Even though users can already scale up/down Pravega components individually by editing the `PravegaCluster` resource. 

> 1. per-component status.  Each of SSS, controller, BK should have status, and by splitting into separate resources, each gets to use the status section in a standard way.

Currently, users can check the `PravegaCluster` status information and, if needed, they can check the `Deployment` and `StatefulSet` resources status used to manage the underlying components. I don't see how individual CRDs would improve the current state.

Moreover, if a user wants to check the availability of a Pravega cluster, they would need to go and check the health of the different components. Whereas now, users only need to check that the Pravega cluster resource reports a healthy status.

> 2. independent versioning of each resource type.

Why would a user update only a single component? IMO, this is error prone and can lead to unstable or incompatible scenarios where a Controller cannot talk to a Segment Store due to different, incompatible versions. I think versioning should be managed at the `PravegaCluster` resource so that updates can be orchestrated as a whole and all components are updated (and rolled back) in sync. 

> 3. simpler reconciliation loop.   the logic of operating each component (SSS,ctrl,BK) could be made more independent.

This is true, but can also be achieved by allowing changes to the underlying `Deployment` and `StatefulSet` and watching them. The complexity of the reconciliation loop can also be reduced by refactoring the current code

> 4. more flexibility.  For example, imagine a scenario where one deploys a tier-2 BK in addition to tier-1 as proposed in [PDP 22 - BK based Storage (Tier 2) for Pravega](https://github.com/pravega/pravega/wiki/PDP-22:-BK-based-Storage-(Tier-2)-for-Pravega).   This could be described more easily if BK resource was a standalone building block.

Tier 2 lifecycle is out of the scope of Pravega and the operator. IMO, a Tier-2 BK cluster should be deployed and managed by a dedicated Bookkeeper operator. Pravega's BK instances are tailored to our needs and I don't think we should attempt to create and maintain a generic BookKeeper CRD and dealing with the inherited complexity that this means.

**Comment by Tristan1900** [comment]
I like to agree with @adrianmo 's opinion. 
1.  I am not sure what are the reasons that users want to control each component's version. Personally, I would easily get frustrated if I have to figure out the compatible version of three components. This adding degree of freedom will decrease usability. 
2. I also feel that the control of the three components are not independent as some control logic needs the coordination of three components. E.g., we need to clean up the metadata in the zookeeper after all pods in Pravega cluster is terminated. In this case, it would be complicated to implement the cleanup routine separately.

**Comment by EronWright** [comment]
The `PravegaCluster` resource is not idiomatic to Kubernetes, there is a stylistic aspect here, and I would appreciate some deference on the creative aspects of Kubernetes integration.

When I say "versioning of each resource type", I mean the `apiVersion` field.   In theory, some resource types could graduate to "v1beta1" and beyond.    I don't really mean the underlying version of the software.

Each of the resource types are an abstraction of some underlying resource(s) (e.g. pods), with a status section that is appropriate for that abstraction.   One of the reasons to have status at the CRD level is to avoid looking at the underlying resources.   My argument is that each of the three resource types have independent status that could be reported in a more standard way.

> This is true, but can also be achieved by allowing changes to the underlying `Deployment` and `StatefulSet` and watching them.

Bad idea, the CRD represents the goal state; the underlying resources are the actual state.  Don't invert that.

I did not say to make the `Bookie` resource be more generic; it may still be designed for use by Pravega.

**Comment by pbelgundi** [comment]
@EronWright While I agree that Pravega cluster spec should expose configuration for Bookeeper, Controller and SegmentStore separately, so that a user knows exactly which component is impacted by a certain configuration change, I do not see the need to make each sub-component a "Custom Resource" or the benefit that brings against the complexity it adds.

**Comment by EronWright** [comment]
To add some detail, here's some examples of what would be possible:
```
$ kubectl scale segmentstores/cluster1 --replicas 5
$ kubectl rollout status segmentstores/cluster1
```

**Comment by pbelgundi** [comment]
`rollout` and `scale` commands on individual components are already supported.
